# @package _global_
defaults: 
  - ../root_config@
  - _self_

test: false # Just for testing, use false for full conversion

chunksize: 10_000_000 # Just for testing, use around 250_000_000 for full conversion with CPU-20-LP

align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

paths:
  concepts: ${oc.env:EHR2MEDS_DATA}/SP/tables
  output: ../data/preMEDS/fetal_data/SP/dmpl

write_file_type: csv 

concepts:
  admissions:
    filename: Mor - CPMI - ADT hændelser.csv
    rename_columns:
      MOR_CPR: subject_id
      Flyt_ind: timestamp_in
      Flyt_ud: timestamp_out
      Afsnit: code
    melt_table:
      - target_name: timestamp
        source_cols: [timestamp_in, timestamp_out]
        prefix_col: code
        prefix_map: {timestamp_in: IN/, timestamp_out: OUT/}

  diagnosis:
    filename: Mor - CPMI - Diagnoseliste.csv
    rename_columns:
      Diagnosekode: code
      Diagnose: fill_code
      Redigeringsdato: timestamp
      MOR_CPR: subject_id

  procedure:
    filename: Mor - CPMI - Procedurer.csv
    rename_columns:
      ProcedureCode: code
      ServiceDate: timestamp
      MOR_CPR: subject_id

  medication:
      filename: Mor - CPMI - Medicin.csv
      rename_columns:
        ATC: code
        Administrationstidspunkt: timestamp
        Bestillingsdato: fill_timestamp
        MOR_CPR: subject_id
      fillna:
        timestamp:
          column: fill_timestamp

  # TODO Add lab values
  labtest:
      filename: Mor - CPMI - Prøvesvar.csv
      rename_columns:
        BestOrd: code
        Prøvetagningstidspunkt: timestamp
        Resultatværdi: numeric_value
        MOR_CPR: subject_id

# TODO Add smoking status
patients_info:
  filename: Mor - CPMI - Patientinfo.csv
  rename_columns:
    MOR_CPR: subject_id
    Fødselsdato: birthdate
    Dødsdato: deathdate
    Køn: gender
