# @package _global_
defaults: 
  - ../root_config@
  - _self_

logging:
  level: INFO
  path: ./outputs/logs

hydra:
  run:
    dir: ./outputs/hydra/fetal_ngc
  output_subdir: hydra

test: false
env: local
run_name: preMEDS_SP_and_SDS
chunksize: 1000000000

paths:
  output: ../data/preMEDS/fetal_data/SDS_SP/dmpl/
  tables_dir: ${oc.env:EHR2MEDS_DATA}/SP/tables      

write_file_type: csv 

align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

concepts:
  admissions:
    filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - ADT hændelser.csv
    rename_columns:
      MOR_CPR: subject_id
      Flyt_ind: timestamp_in
      Flyt_ud: timestamp_out
      Afsnit: code
    melt_table:
      - target_name: timestamp
        source_cols: [timestamp_in, timestamp_out]
        prefix_col: code
        prefix_map: {timestamp_in: IN/, timestamp_out: OUT/}
    code_prefix: "ADM/"

  diagnosis:
    filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - Diagnoseliste.csv
    rename_columns:
      Diagnosekode: code
      Diagnose: fill_code
      Redigeringsdato: timestamp
      MOR_CPR: subject_id
    code_prefix: "D/"

  procedure:
    filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - Procedurer.csv
    rename_columns:
      ProcedureCode: code
      ServiceDate: timestamp
      MOR_CPR: subject_id
    code_prefix: "P/"

  medication:
    filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - Medicin.csv
    rename_columns:
      ATC: code
      Administrationstidspunkt: timestamp
      Bestillingsdato: fill_timestamp
      MOR_CPR: subject_id
    code_prefix: "M/"
    fillna:
      timestamp:
        column: fill_timestamp

  # TODO Add lab values
  labtest:
    filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - Prøvesvar.csv
    rename_columns:
      BestOrd: code
      Prøvetagningstidspunkt: timestamp
      Resultatværdi: numeric_value
      MOR_CPR: subject_id
    code_prefix: "LAB/"

  SDS_diagnoser:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/diagnoser.csv               
    rename_columns:
      diagnosekode: code
      diagnosetype: diagnosetype
      dw_ek_kontakt: contact_id
    code_prefix: "RD/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/kontakter_all.csv           
        join_on: dw_ek_kontakt
        target_column: cpr
        rename_to: subject_id
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/kontakter_all.csv
        join_on: dw_ek_kontakt
        target_column: dato_slut      
        rename_to: timestamp
        drop_source: true
    unroll_columns:
      - column: diagnosetype
        prefix: "RD_TYPE/"

  SDS_t_diag:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/t_diag.csv               
    rename_columns:
      C_DIAG: c_diag
      C_TILDIAG: c_tildiag
      C_DIAGTYPE: c_diagtype
      V_RECNUM: contact_id
    code_prefix: "RD/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/t_adm.csv
        join_on: K_RECNUM
        target_column: V_CPR
        rename_to: subject_id
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/t_adm.csv
        join_on: K_RECNUM
        target_column: D_UDDTO 
        rename_to: timestamp
        drop_source: true
    unroll_columns:
      - column: c_diagtype
        prefix: "RD_TYPE/"
      - column: c_tildiag #NOTE: treated as also being a diagnosis to merge better with LPR3
        prefix: "RD/"
      - column: c_diag
        prefix: "RD/"

  SDS_kontakter:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/kontakter_all.csv               
    rename_columns:
      cpr: subject_id
      dato_start: date_start
      tidspunkt_start: time_start
      aktionsdiagnose: code
      kontaktaarsag: contact_reason
      prioritet: priority
      kontakttype: contact_type
      hovedspeciale_ans: clinical_specialty
      region_ans: region_code
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    unroll_columns:
      - column: contact_reason
        prefix: "RC_REASON/"
      - column: priority
        prefix: "RC_PRIO/"
      - column: contact_type
        prefix: "RC_TYPE/"
      - column: clinical_specialty
        prefix: "RC_SPEC/"
      - column: region_code
        prefix: "RC_REG/"
    code_prefix: "RC/"

  SDS_t_adm:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/t_adm.csv               
    rename_columns:
      V_CPR: subject_id
      D_INDDTO: date_start
      V_INDTIME: v_indtime
      V_INDMINUT: v_indminut
      C_ADIAG: code
      C_KONTAARS: contact_reason
      C_PATTYPE: patient_type 
      C_INDM: priority # NOTE: mapped to priority
      C_SPEC: clinical_specialty
      C_SGH: hospital_code
      K_RECNUM: contact_id
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_indtime
        minute_col: v_indminut
        drop_original: true
    unroll_columns:
      - column: contact_reason
        prefix: "RC_REASON/"
      - column: patient_type
        prefix: "RC_ADM_TYPE/"
      - column: priority
        prefix: "RC_PRIO/"
      - column: clinical_specialty
        prefix: "RC_SPEC/"
      - column: hospital_code
        prefix: "RC_SGH/"
    code_prefix: "RC_ADM/"

  SDS_t_sksopr:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/t_sksopr.csv   
    rename_columns:
      C_OPR: code
      D_ODTO: date_start
      V_OTIME: v_otime
      V_OMINUT: v_ominut
      V_RECNUM: contact_id
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_otime
        minute_col: v_ominut
        drop_original: true
    code_prefix: "RPS/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/t_adm.csv
        join_on: K_RECNUM
        target_column: V_CPR
        rename_to: subject_id
        drop_source: true

  SDS_t_sksube:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/t_sksube.csv   
    rename_columns:
      C_OPR: code
      C_OPRART: procedure_type
      D_ODTO: date_start
      V_OTIME: v_otime
      V_OMINUT: v_ominut
      V_RECNUM: contact_id
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_otime
        minute_col: v_ominut
        drop_original: true
    code_prefix: "RPO/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/t_adm.csv
        join_on: K_RECNUM
        target_column: V_CPR
        rename_to: subject_id
        drop_source: true
    fillna:
      procedure_type:
        value: "P" 

  SDS_ekokur:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/ekokur_all.csv                  
    rename_columns:
      cpr: subject_id
      vnr: vnr_code
      eksd: timestamp
    mappings:
      - source_column: vnr_code
        how: left
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/laegemiddeloplysninger.csv   
        join_on: vnr
        target_column: pname
        rename_to: code
        drop_source: false
    code_prefix: "RM/"

  SDS_procedurer_kirurgi:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/procedurer_kirurgi.csv      
    rename_columns:
      procedurekode: code
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPS/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/kontakter_all.csv
        join_on: dw_ek_kontakt
        target_column: cpr
        rename_to: subject_id
        drop_source: true

  SDS_procedurer_andre:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/procedurer_andre.csv        
    rename_columns:
      procedurekode: code
      proceduretype: procedure_type
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPO/"
    mappings:
      - source_column: contact_id
        via_file: ${paths.tables_dir}/SDS/registers_pseudonymized/kontakter_all.csv
        join_on: dw_ek_kontakt
        target_column: cpr
        rename_to: subject_id
        drop_source: true

  SDS_laboratorieproevesvar:
    filename: ${paths.tables_dir}/SDS/registers_pseudonymized/lab_dm_forsker_all.csv
    rename_columns:
      ANALYSISCODE: code
      VALUE: numeric_value
      SAMPLINGDATE: samplingdate
      SAMPLINGTIME: samplingtime
      PATIENT_CPR: subject_id
    combine_datetime:
      timestamp:
        date_col: samplingdate
        time_col: samplingtime
        drop_original: true
    code_prefix: "L/"
    numeric_columns: [numeric_value]


# TODO Add smoking status
# Todo support multiple patient_infos
patients_info:
  filename: ${paths.tables_dir}/SP/tables/Mor - CPMI - Patientinfo.csv
  rename_columns:
    MOR_CPR: subject_id
    Fødselsdato: birthdate
    Dødsdato: deathdate
    Køn: gender