# @package _global_
defaults: 
  - ../root_config@
  - _self_

test: false # Just for testing, use false for full conversion

chunksize: 10_000 # Just for testing, use around 250_000_000 for full conversion with CPU-20-LP

align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

paths:
  concepts: ${oc.env:EHR2MEDS_DATA}/raw/fetal_data/SP  
  output: ${oc.env:EHR2MEDS_DATA}/preMEDS/fetal_data/SP

write_file_type: csv 

concepts:
  diagnosis:
    filename: diagnosis.csv
    rename_columns:
      Diagnosekode: code
      Redigeringsdato: timestamp
      CPR: subject_id
    file_info:
      sep: "\t"
      encoding: "iso8859-1"

  procedure:
    filename: procedure.csv
    rename_columns:
      Procedurekode: code
      Redigeringsdato: timestamp
      CPR: subject_id


  admissions:
    filename: admissions.csv
    rename_columns:
      Flyt_ind: timestamp_in
      Flyt_ud: timestamp_out
      Afsnit: section
      ADT_haendelse: type
      CPR: subject_id 
    use_adm_move: true

  labtest:
    filename: labtest.asc
    rename_columns:
      BestOrd: code
      Bestillingsdato: timestamp
      CPR: subject_id
      Resultatværdi: numeric_value
    file_info:
      sep: "|"
      encoding: "latin1"


patients_info:
  filename: patient_info.csv
  rename_columns:
    CPR: subject_id
    Birthdate: birthdate
    Deathdate: deathdate
    Gender: gender
