# @package _global_
defaults: 
  - ../root_config@
  - _self_

logging:
  level: INFO
  path: ./outputs/logs


test: false
env: local
run_name: preMEDS_registers_only
chunksize: 1000000000

paths:
  output: ${oc.env:EHR2MEDS_DATA}/preMEDS/SDS
  pid_link: data/mapping/mapping.parquet

  concepts: ${oc.env:EHR2MEDS_DATA}/raw/sp         
  register_concepts: ${oc.env:EHR2MEDS_DATA}/raw/registers   
  file_type: parquet                  

write_file_type: parquet 

pid_link: 
  join_col: pseudoid
  target_col: patientid


align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

# concepts:
  # SDS_laboratorieproevesvar:
  #     filename: SDS_laboratorieproevesvar.parquet
  #     rename_columns:
  #       analysiscode: code
  #       samplevalue: numeric_value
  #       patientid: subject_id
  #     combine_datetime:
  #       timestamp:
  #         date_col: samplingdate
  #         time_col: samplingtime
  #         drop_original: true
  #     code_prefix: "L/"
  #     numeric_columns: [numeric_value]

register_concepts:
  SDS_dimpatologiskdiagnose:
      filename: SDS_dimpatologiskdiagnose.parquet
      rename_columns:
        diagnose_snomed_kode: code
        dw_ek_rekvisition: contact_id
      code_prefix: "PAT/"
      mappings:
        - source_column: contact_id
          via_file: SDS_fctrekvisition.parquet
          join_on: dw_ek_rekvisition
          target_column: patientid
          rename_to: subject_id
        - source_column: contact_id
          via_file: SDS_fctrekvisition.parquet
          join_on: dw_ek_rekvisition
          target_column: datotid_modtagelse # NOTE: This should probably be a complete timestamp, which it is not. 
          rename_to: timestamp
          drop_source: false
        - source_column: contact_id
          via_file: SDS_fctrekvisition.parquet
          join_on: dw_ek_rekvisition
          target_column: dato_modtagelse # NOTE: This should probably be a complete timestamp, which it is not. 
          rename_to: timestamp_fallback
          drop_source: true
      pad_values:
        timestamp_fallback:
          suffix: "T00:00:00"
          unless_contains: ":"
      fillna:
        timestamp:
          column: timestamp_fallback

  SDS_diagnoser:
    filename: SDS_diagnoser.parquet               
    rename_columns:
      diagnosekode: code
      diagnosetype: diagnosetype
      dw_ek_kontakt: contact_id
    code_prefix: "RD/"
    mappings:
      - source_column: contact_id
        via_file: SDS_kontakter.parquet           
        join_on: dw_ek_kontakt
        target_column: patientid
        rename_to: subject_id
      - source_column: contact_id
        via_file: SDS_kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: dato_slut      # interesting that this is dato_slut? Is that a feature or a bug?
        rename_to: timestamp
        drop_source: true
    unroll_columns:
      - column: diagnosetype
        prefix: "RD_TYPE/"

  SDS_t_diag:
    filename: SDS_t_diag.parquet               
    rename_columns:
      c_diag: c_diag
      c_tildiag: c_tildiag
      c_diagtype: c_diagtype
      v_recnum: contact_id
    code_prefix: "RD/"
    mappings:
      - source_column: contact_id
        via_file: SDS_t_adm.parquet
        join_on: k_recnum
        target_column: patientid
        rename_to: subject_id
      - source_column: contact_id
        via_file: SDS_t_adm.parquet
        join_on: k_recnum
        target_column: d_uddto 
        rename_to: timestamp
        drop_source: true
    unroll_columns:
      - column: c_diagtype
        prefix: "RD_TYPE/"
      - column: c_tildiag #NOTE: treated as also being a diagnosis to merge better with LPR3
        prefix: "RD/"
      - column: c_diag
        prefix: "RD/"

  SDS_kontakter:
    filename: SDS_kontakter.parquet               
    rename_columns:
      patientid: subject_id
      dato_start: date_start
      tidspunkt_start: time_start
      aktionsdiagnose: code
      kontaktaarsag: contact_reason
      prioritet: priority
      kontakttype: contact_type
      hovedspeciale_ans: clinical_specialty
      region_ans: region_code
      dw_ek_kontakt: contact_id
      dw_ek_forloeb: course_id # new addition 
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    unroll_columns:
      - column: contact_reason
        prefix: "RC_REASON/"
      - column: priority
        prefix: "RC_PRIO/"
      - column: contact_type
        prefix: "RC_TYPE/"
      - column: clinical_specialty
        prefix: "RC_SPEC/"
      - column: region_code
        prefix: "RC_REG/"
    code_prefix: "RC/"

  ## NOTE: adding administration data, which is equivalent to previous contacts
  # Currently just using the same prefix.


  SDS_t_adm:
    filename: SDS_t_adm.parquet               # data/registers/SDS_t_adm.parquet
    normalize_columns:
      - c_spec
      - c_indm
      - c_kontaars
    value_map:
      c_spec:
        "01": "intern medicin"
        "02": "geriatri"
        "04": "hæmatologi"
        "05": "infektionsmedicin"
        "06": "kardiologi"
        "07": "medicinsk allergologi"
        "08": "endokrinologi"
        "09": "medicinsk gastroenterologi"
        "10": "lungesygdomme"
        "11": "nefrologi"
        "12": "reumatologi"
        "15": "akutmedicin"
        "18": "dermato-venerologi"
        "20": "neurologi"
        "22": "klinisk onkologi"
        "30": "kirurgi"
        "31": "karkirurgi"
        "32": "kirurgisk gastroenterologi"
        "33": "plastikkirurgi"
        "34": "thoraxkirurgi"
        "35": "urologi"
        "38": "gynækologi og obstetrik"
        "40": "neurokirurgi"
        "42": "ortopædisk kirurgi"
        "44": "oftalmologi"
        "46": "oto-rhino-laryngologi"
        "48": "tand-, mund- og kæbekirurgi"
        "50": "psykiatri"
        "52": "børne- og ungdomspsykiatri"
        "60": "klinisk biokemi"
        "61": "klinisk fysiologi og nuklearmedicin"
        "62": "klinisk immunologi"
        "63": "klinisk mikrobiologi"
        "64": "klinisk neurofysiologi"
        "66": "radiologi"
        "67": "klinisk farmakologi"
        "68": "klinisk genetik"
        "80": "pædiatri"
        "84": "anæstesiologi"
        "86": "arbejdsmedicin"
        "90": "almen medicin"
        "91": "samfundsmedicin"
      c_indm: # map emergency vs planned visits to LPR3
        "1": "ATA1"
        "2": "ATA3"
      c_kontaars:
        "1": "ALCC01"
        "2": "ALCC02"
        "3": "ALCC03"
        "4": "ALCC04"
        "6": "ALCC90"
        "7": "ALCC90"
        "8": "ALCC90"
        "9": "ALCC90"
    rename_columns:
      patientid: subject_id
      d_inddto: date_start
      v_indtime: v_indtime
      v_indminut: v_indminut
      c_adiag: code
      c_kontaars: contact_reason
      c_pattype: patient_type # NOTE: should be mapped to contatct type
      c_indm: priority # NOTE: needs mapping to work
      c_spec: clinical_specialty
      c_sgh: hospital_code
      k_recnum: contact_id
    mappings:
    - source_column: hospital_code    # whatever c_shak is renamed to
      via_file: shak_to_region.parquet
      join_on: kode
      target_column: region
      rename_to: region_code
      drop_source: true
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_indtime
        minute_col: v_indminut
        # time_col: time_start
        drop_original: true
    unroll_columns:
      - column: contact_reason
        prefix: "RC_REASON/"
      - column: patient_type
        prefix: "RC_ADM_TYPE/"
      - column: priority
        prefix: "RC_PRIO/"
      - column: clinical_specialty
        prefix: "RC_SPEC/"
      - column: region_code
        prefix: "RC_REG/"
    code_prefix: "RC_ADM/"

  SDS_t_sksopr:
    filename: SDS_t_sksopr.parquet      # data/registers/procedurer_kirurgi.parquet
    rename_columns:
      c_opr: code
      d_odto: date_start
      v_otime: v_otime
      v_ominut: v_ominut
      # v_estimated_time: time_start
      v_recnum: contact_id
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_otime
        minute_col: v_ominut
        drop_original: true
    code_prefix: "RPS/"
    mappings:
      - source_column: contact_id
        via_file: SDS_t_adm.parquet
        join_on: k_recnum
        target_column: patientid
        rename_to: subject_id
        drop_source: true

  SDS_t_sksube:
    filename:   SDS_t_sksube.parquet        # data/registers/procedurer_andre.parquet
    rename_columns:
      c_opr: code
      c_oprart: procedure_type
      d_odto: date_start
      v_otime: v_otime
      v_ominut: v_ominut
      v_recnum: contact_id
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: v_otime
        minute_col: v_ominut
        drop_original: true
    code_prefix: "RPO/"
    mappings:
      - source_column: contact_id
        via_file: SDS_t_adm.parquet
        join_on: k_recnum
        target_column: patientid
        rename_to: subject_id
        drop_source: true
    fillna:
      procedure_type:
        value: "P" # LPR convention; no code is primary procedure 

  SDS_ekokur:
    filename: SDS_ekokur.parquet                  # data/registers/epikur.parquet
    rename_columns:
      patientid: subject_id
      vnr: vnr_code
      eksd: timestamp
    mappings:
      - source_column: vnr_code
        how: left
        via_file: laegemiddeloplysninger.parquet   # data/registers/laegemiddeloplysninger.parquet
        join_on: vnr
        target_column: pname
        rename_to: code
        drop_source: false
    code_prefix: "RM/"

  SDS_procedurer_kirurgi:
    filename: SDS_procedurer_kirurgi.parquet      # data/registers/procedurer_kirurgi.parquet
    rename_columns:
      procedurekode: code
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPS/"
    mappings:
      - source_column: contact_id
        via_file: SDS_kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: patientid
        rename_to: subject_id
        drop_source: true

  SDS_procedurer_andre:
    filename: SDS_procedurer_andre.parquet        # data/registers/procedurer_andre.parquet
    rename_columns:
      procedurekode: code
      proceduretype: procedure_type
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPO/"
    mappings:
      - source_column: contact_id
        via_file: SDS_kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: patientid
        rename_to: subject_id
        drop_source: true

  SDS_laboratorieproevesvar:
    filename: SDS_laboratorieproevesvar.parquet
    rename_columns:
      analysiscode: code
      samplevalue: numeric_value
      samplingdate: samplingdate
      samplingtime: samplingtime
      patientid: subject_id
    combine_datetime:
      timestamp:
        date_col: samplingdate
        time_col: samplingtime
        drop_original: true
    code_prefix: "L/"
    numeric_columns: [numeric_value]

patients_info:
  filename: CPMI_PatientInfo.parquet
  rename_columns:
    patientid: subject_id
    Fødselsdato: birthdate
    Dødsdato: deathdate
    Køn: gender
  file_type: parquet