# @package _global_
defaults: 
  - ../root_config@
  - _self_

logging:
  level: INFO
  path: ./outputs/logs


test: false
env: local
run_name: preMEDS_phair_light
chunksize: 10_000_000

paths:
  output: ${oc.env:EHR2MEDS_DATA}/preMEDS/PHAIR_light

  concepts: ${oc.env:EHR2MEDS_DATA}/raw/sp         
  register_concepts: ${oc.env:EHR2MEDS_DATA}/raw/registers   
  file_type: parquet                  

write_file_type: parquet 


align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

register_concepts:
  diagnoser: 
    filename: diagnoser.parquet # LPR3
    rename_columns:
      dw_ek_kontakt: contact_id
      diagnosekode: code
      diagnosetype: diagnosis_type
    code_prefix: "RD/"
    mappings:
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: cpr
      rename_to: subject_id
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: dato_start
      rename_to: date_start
      drop_source: true
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: tidspunkt_start
      rename_to: time_start
      drop_source: true
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    unroll_columns: 
    - column: diagnosetype 
      prefix: "RD_TYPE/"

  t_diag:
    filename: t_diag.parquet # LPR              
    rename_columns:
      v_recnum: record_number
      c_diag: code
      c_diagtype: diagnosis_type
      c_tildiag: diagnosis_additional
    code_prefix: "RD/"
    mappings: 
    - source_column: record_number
      via_file: t_adm.parquet
      join_on: k_recnum
      target_column: v_cpr
      rename_to: subject_id
    - source_column: record_number
      via_file: t_adm.parquet
      join_on: k_recnum 
      target_column: v_admdate
      rename_to: date_start
      drop_source: true
    

