# @package _global_
defaults: 
  - ../root_config@
  - _self_

logging:
  level: INFO
  path: ./outputs/logs


test: false
env: local
run_name: preMEDS_phair_light
chunksize: 10_000_000

paths:
  output: ${oc.env:EHR2MEDS_DATA}/preMEDS/PHAIR_light

  concepts: ${oc.env:EHR2MEDS_DATA}/raw/sp         
  register_concepts: ${oc.env:EHR2MEDS_DATA}/raw/registers   
  file_type: parquet                  

write_file_type: parquet 


align_timestamps: # removes information that is not in the global format
  names: [timestamp]
  format: "%Y-%m-%d %H:%M:%S"

register_concepts:
  epikur:
    filename: epikur.parquet
    rename_columns:
      cpr: subject_id
      eksd: timestamp
      atc: code
    code_prefix: "PM/" # prescription medication

  indberetningmedpris:
    filename: indberetningmedpris.parquet
    rename_columns:
      v_cpr: subject_id
      d_ord_start: timestamp
      c_atc: code
    code_prefix: "AM/" # administered medication

  t_diag:
    filename: t_diag.parquet # LPR1+2             
    rename_columns:
      v_recnum: record_number
      c_diag: code
    code_prefix: "DIAG/"
    mappings:
    - source_column: record_number
      via_file: t_adm.parquet
      join_on: k_recnum
      target_column: v_cpr # cpr
      rename_to: subject_id
    - source_column: record_number 
      via_file: t_adm.parquet
      join_on: k_recnum 
      target_column: t_inddto # date
      rename_to: date_start
    - source_column: record_number 
      via_file: t_adm.parquet
      join_on: k_recnum
      target_column: v_indtime # hour
      rename_to: hour_start
    - source_column: record_number 
      via_file: t_adm.parquet
      join_on: k_recnum 
      target_column: v_indminut # minute
      rename_to: minute_start
      drop_source: true
    combine_datetime_parts:
      timestamp:
        date_col: date_start
        hour_col: hour_start
        minute_col: minute_start
        drop_original: true
    
  diagnoser: 
    filename: diagnoser.parquet # LPR3
    rename_columns:
      dw_ek_kontakt: contact_id
      diagnosekode: code
    code_prefix: "DIAG/"
    mappings:
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: cpr # cpr
      rename_to: subject_id
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: dato_start # date
      rename_to: date_start
    - source_column: contact_id
      via_file: kontakter.parquet
      join_on: dw_ek_kontakt
      target_column: tidspunkt_start # time
      rename_to: time_start
      drop_source: true
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true