channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11.10
  - pip
  - pip:
      - meds==0.3.3
      - meds-transforms==0.1.1
      - meds_reader
      - pandas
      - numpy
      - pyarrow
      - tqdm
      - torch
name: ehr2meds