channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11.10
  - pip
  - pip:
      - meds==0.3.3
      - meds-transforms==0.1.1
      - meds_reader
      - pandas=3.0.0
      - numpy=2.4.2
      - pyarrow=23.0.1
      - tqdm=4.67.3
      - fastparquet=2025.12.0
      - PyYAML=6.0.3
name: ehr2meds