channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.11
  - pip:
      - meds
      - meds-transforms
      - meds_reader
      - azureml-core
      - azureml-defaults
      - azureml-mlflow
      - pandas
      - torch
      - tqdm
name: MEDS