[build-system]
requires = ["setuptools>=64.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ehr2meds"
version= "1.1.0"
description = "A preprocessing pipeline for electronic health records."
authors = [
    { name = "Sebastian Llambias", email = "snl@di.ku.dk" },
    { name = "Mikkel Odgaard"},
    { name = "Maria Montgomery" },
    { name = "Mikkel Werling"},
    { name = "Katja Jagd"},
]
# Project is intended to run on Python 3.12 only.
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas>=3.0.3",
    "numpy>=2.5.0",
    "pyarrow>=24.0.0",
    "tqdm>=4.68.3",
    "meds-extract==0.6.2", # uses meds==0.4.1 and meds-transforms==0.6.7
    "python-dotenv>=1.0.0",
    "hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff==0.15.1",
]

[tool.setuptools_scm]

[tool.setuptools.packages.find]
where = ["."]


[tool.ruff]
line-length = 127

[project.entry-points."MEDS_transforms.stages"]
add_source_row_id = "ehr2meds.meds_stages.add_source_row_id:main"
bin_numeric_values_fast = "ehr2meds.meds_stages.bin_numeric_values_fast:stage"

[tool.ruff.lint]
# "E": style/error codes (PEP 8–type errors, e.g. if x == None).
# "F": Pyflakes-style errors (unused variables, undefined names, etc.).
# "I": import-related issues (import order, duplicates, etc.).
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
no-sections = true
combine-as-imports = true

[tool.ruff.format]
# quote-style = "double": Ruff prefers " over ' when it reformats strings, as long as it’s safe.
# indent-style = "space": indentation uses spaces, not tabs.
quote-style = "double"
indent-style = "space"