# @package _global_
defaults: 
  - ../root_config@
  - _self_

paths:
  output: ${oc.env:EHR2MEDS_DATA}/raw/fetal_data/SP

data: 
  patient_info:
    N: 25
    columns:
      CPR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      Birthdate:
        type: rand_date
      Deathdate:
        type: greater_than_date
        match:
          min_date: Birthdate
        corruptions:
          - type: insert_nan
            args:
              probability: 0.8
      Gender:
        type: choice
        args:
          options: ["M", "K"]
      Ethnicity:
        type: choice
        args:
          options: ["Unspecified", "Nordeuropa", "Asien", "Mellemøsten"]

linked_data:
  diagnosis:
    N: 100
    columns:
      Diagnosekode:
        type: medical_code
        args:
          prefix: "D"
      Redigeringsdato:
        type: rand_datetime 
    linked_columns:
      CPR:
        type: choice
        file: patient_info
        linked_on: [CPR]

  procedure:
    N: 100
    columns:
      Procedurekode:
        type: medical_code
        args:
          prefix: "P"
      Redigeringsdato:
        type: rand_datetime
    linked_columns:
      CPR:
        type: choice
        file: patient_info
        linked_on: [CPR]

  labtest:
    N: 20
    columns:
      BestOrd:
        type: rand_string
        args:
          min_length: 20
          max_length: 100
      Bestillingsdato:
        type: rand_datetime
      Enhed:
        type: choice
        args:
          options: ["fl", "mmol/l", "10^9/l", "fmol", "U/L"]
      Resultatværdi:
        type: mix_function
        args:
          functions:
            - type: rand_float
              args:
                min_val: 0.001
                max_val: 100
            - type: rand_int
              args:
                min_val: 0
                max_val: 300
            - type: choice
              args:
                options: ["Positive", "Negative", "Ikke påvist", "påvist", "0 Rhd pos"]
          probabilities: [0.4, 0.4, 0.2]
    linked_columns:
      CPR:
        type: choice
        file: patient_info
        linked_on: [CPR]

  notes:
    N: 20
    columns:
      Linjenummer:
        type: rand_int
        args:
          min_val: 1
          max_val: 10
      Redigeringstidspunkt:
        type: rand_datetime
      Notetype:
        type: choice
        args:
          options: ["Opfølgning", "Indlæggelse", "Operation"]
      Speciale:
        type: choice
        args:
          options: ["Nefrologi", "Gastroenterologi", "Kardiologi", "Endokrinologi", "Nervensundhed", "Andet"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
      note:
        type: rand_string
        args:
          min_length: 10
          max_length: 3000
    linked_columns:
      CPR:
        type: choice
        file: patient_info
        linked_on: [CPR]