# @package _global_
defaults: 
  - ../root_config@
  - _self_

paths:
  output: ${oc.env:EHR2MEDS_DATA}/raw/fetal_data/SDS_AND_SP_from_population

N: 1000 
linked_data:
  ekokur_all:
    N: ${N}
    columns:
      vnr:
        type: rand_int
        args:
          min_val: 1
          max_val: 10
      eksd:
        type: rand_date
      pname:
        type: choice
        args:
          options: ["Dulcolax", "Telefonreceptgebyr"]
    linked_columns:
      cpr:
        type: choice
        file: Population
        linked_on: MOR_CPR
      

  epikur_1:
    N: ${N}
    columns:
      atc:
        type: choice
        args:
          options: ["G03DA04", "A06AB02", "S01AA01", "B03AA07", "D01AE15"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      eksd:
        type: rand_date
        args:
          start: 2010
    linked_columns:
      cpr:
        type: choice
        file: Population
        linked_on: MOR_CPR

  epikur_2:
    N: ${N}
    columns:
      atc:
        type: choice
        args:
          options: ["G03DA04", "A06AB02", "S01AA01", "B03AA07", "D01AE15"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      eksd:
        type: rand_date
        args:
          start: 2010
    linked_columns:
      cpr:
        type: choice
        file: Population
        linked_on: MOR_CPR

  epikur_3:
    N: ${N}
    columns:
      atc:
        type: choice
        args:
          options: ["G03DA04", "A06AB02", "S01AA01", "B03AA07", "D01AE15"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      eksd:
        type: rand_date
        args:
          start: 2010
    linked_columns:
      cpr:
        type: choice
        file: Population
        linked_on: MOR_CPR


  graviditetskomplikation:
    N: ${N}
    columns:
      SKSKODE:
        type: choice
        args:
          options: ["DZ358Q", "DO144", "DO141", "DO140", "DO139"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
    linked_columns:
      FK_MFR:
        type: choice
        file: mfr
        linked_on: PK_MFR

  igangsaettelse:
    N: ${N}
    columns:
      SKSKODE:
        type: choice
        args:
          options: ["KMAC", "BKHD", "OTHER"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
    linked_columns:
      FK_MFR:
        type: choice
        file: mfr
        linked_on: PK_MFR

  kejsersnit:
    N: ${N}
    columns:
      SKSKODE:
        type: choice
        args:
          options: ["KMCA10A", "KMCARANDOM", "KMCAOTHER", "STUFF"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
    linked_columns:
      FK_MFR:
        type: choice
        file: mfr
        linked_on: PK_MFR

  laegemiddeloplysninger:
    N: ${N}
    columns:
      atc:
        type: choice
        args:
          options: ["G03DA04", "A06AB02", "S01AA01", "B03AA07", "D01AE15"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      pname:
        type: choice
        args:
          options: ["Dulcolax", "Telefonreceptgebyr"]
      vnr:
        type: rand_int
        args:
          min_val: 1
          max_val: 10
    linked_columns:
      cpr:
        type: choice
        file: Population
        linked_on: MOR_CPR
    save_info:
      args:
        sep: "\t"
        encoding: "iso8859-1"

  Mor - Alkohol: 
    N: ${N}
    columns:
      "Alkohol - Antal ugentlige genstande":
        type: rand_int
        args:
          min_val: 0
          max_val: 10
        corruptions:
          - type: insert_nan
            args:
              probability: 0.8
      "Kontakt dato":
        type: rand_datetimeseconds
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR

  Mor - CPMI - Diagnoseliste:
    N: ${N}
    columns:
      Diagnosekode:
        type: choice
        args:
          options: ["DS931H","DO837", "DO847","DO420", "DO422", "DO424", "DO601"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      Diagnose:
        type: choice
        args:
          options: ["Normal graviditet, førstegangsfødende (DZ340)", "(kun LPR2) Eet levendefødt barn (DZ370)"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      Noteret_dato:
        type: rand_datetimeseconds
      Redigeringsdato:
        type: rand_datetimeseconds
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR

  Mor - CPMI - Procedurer:
    N: ${N}
    columns:
      ProcedureCode:
        type: choice
        args:
          options: ["KMCA00", "KMCA96", "KMCA10C", "KMCA30", "BRFAO", "BABZ00", "KMAC00", "KMAC96A", "BKHD2", "BKHD20", "KMCA10D", "KMCA10E"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      ServiceDate:
        type: rand_datetimeseconds
      ServiceDatetime:
        type: rand_datetimeseconds
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR


  Mor - CPMI - Vital parametre:
    N: ${N}
    columns:
      Registreringstidspunkt:
        type: rand_datetime
        args:
          start: 2010
      Værdi:
        type: choice
        args:
          options: ["101/67", "120/80", "110/70", "130/85"]
      Vital_parametre:
        type: choice
        args:
          options: ["BT", "NIBP", "BMI"]
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR

  Mor - Fødselsresume - DEL 1:
    N: ${N}
    columns:
      Køn:
        type: choice
        args:
          options: ["Mand", "Kvinde"]
      Måde:
        type: choice
        args:
          options: ["Vaginal, igangsat", "Vaginal, igangsat (Udgået)", "Biokemisk", "Medicinsk behandling", "Elektivt sectio"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      Foster nr.:
        type: choice
        args:
          options: ["Foster 1", "Foster 2", "Foster 3", "Foster 4"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.25
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR
      BABY_Fødsel_ID:
        type: choice
        file: Population
        linked_on: BABY_Fødsel_ID

  Mor - Obstetrisk Historik DEL 1:
    N: ${N}
    columns:
      Flerfold: 
        type: rand_int
        args:
          min_val: 1
          max_val: 4
        corruptions:
          - type: insert_nan
            args:
              probability: 0.6
      Kontakt dato:
        type: rand_date
        args:
          start: 2010
      Para:
        type: rand_int
        args:
          min_val: 0
          max_val: 5
        corruptions:
          - type: insert_missing
            args:
              probability: 0.15
      Præterm:
        type: rand_int
        args:
          min_val: 0
          max_val: 1
    linked_columns:
      MOR_CPR:
        type: choice
        file: Mor - CPMI - Patientinfo
        linked_on: MOR_CPR

  Mor - Obstetrisk Historik DEL 2:
    N: ${N}
    columns:
      Gestationsalder:
        type: choice
        args:
          options: ["34w0d", "35w0d", "36w0d", "37w0d", "38w0d", "39w0d", "40w0d", "41w0d", "42w0d",
                    "34w6d", "35w6d", "36w6d", "37w6d", "38w6d", "39w6d", "40w6d", "41w6d", "42w6d", 
                    "32w3d", "33w3d", "34w3d", "35w3d", "36w3d", "37w3d", "38w3d", "39w3d", "40w3d", "41w3d", "42w3d"]
      Dato:
        type: rand_date
        args:
          start: 2010
    linked_columns:
      MOR_CPR:
        type: choice
        file: Mor - CPMI - Patientinfo
        linked_on: MOR_CPR
  
  Mor - Rygning:
    N: ${N}
    columns:
      Rygestatus: 
        type: choice
        args: 
          options: ["Tidligere", "Nogle dage", "Aldrig"]
      "Kontakt dato":
        type: rand_datetimeseconds
        args:
          start: 2010
    linked_columns:
      MOR_CPR:
        type: choice
        file: Mor - CPMI - Patientinfo
        linked_on: MOR_CPR

  Mor - Patientinfo tillæg til CPMI:
    N: ${N}
    columns:
      "Dato for seneste opdatering":
        type: rand_datetime
        args:
          start: 2010
      Alkohol - Antal ugentlige genstande: 
        type: rand_int
        args:
          min_val: 0
          max_val: 10
        corruptions:
          - type: insert_nan
            args:
              probability: 0.8
      Rygestatus: 
        type: choice
        args: 
          options: ["Tidligere", "Nogle dage", "Aldrig"]
      Etnicitet:
        type: choice
        args:
          options: ["Unspecified", "Nordeuropa", "Asien", "Mellemøsten"]
    linked_columns:
      MOR_CPR:
        type: choice
        file: Mor - CPMI - Patientinfo
        linked_on: MOR_CPR

  Mor - Yderligere variable vurderingsskema:
    N: ${N}
    columns:
      Værdi:
        type: mix_function
        args:
          functions:
            - type: rand_float
              args:
                min_val: 0
                max_val: 100
            - type: choice
              args:
                options: [".", "", "<25", ">25", "positive", "negative", "hovedstilling", "Lejeændring;STAN;HSP"]
          probabilities: [0.9, 0.1]
      Registrering:
        type: choice
        args:
          options: ["Cervix i mm", "Handlinger"]
      Registreringstidspunkt:
        type: rand_datetime
        args:
          start: 2010
    linked_columns:
      MOR_CPR:
        type: choice
        file: Mor - CPMI - Patientinfo
        linked_on: MOR_CPR

  notes:
    N: ${N}
    columns:
      Linjenummer:
        type: rand_int
        args:
          min_val: 1
          max_val: 10
      Redigeringstidspunkt:
        type: rand_datetime
      Notetype:
        type: choice
        args:
          options: ["Opfølgning", "Indlæggelse", "Operation"]
      Speciale:
        type: choice
        args:
          options: ["Nefrologi", "Gastroenterologi", "Kardiologi", "Endokrinologi", "Nervensundhed", "Andet"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
      note:
        type: rand_string
        args:
          min_length: 10
          max_length: 3000
    linked_columns:
      MOR_CPR:
        type: choice
        file: Population
        linked_on: MOR_CPR

  t_afl:
    N: ${N}
    columns:
      C_TILOPR:
        type: choice
        args:
          options: ["KLDD10A", "KLDD10B", "KMAB00", "KMAB01", "KLDD20", "KMAB03","KMCA10D”, “KMCA10E"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.1
      D_ODTO:
        type: rand_datetime
        args:
          start: 2010
    linked_columns:
      V_RECNUM:
        type: choice
        file: Population
        linked_on: MOR_Fødsel_ID 

  t_diag:
    N: ${N}
    columns:
      C_DIAG:
        type: choice
        args:
          options: ["DZ016", "DZ090","DO343C", "DO420", "DO422", "DO424","DO601"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.05
      C_DIAGTYPE:
        type: choice
        args:
          options: ["A", "B", "+"]
      C_TILDIAG:
        type: choice
        args:
          options: ["KNDJ73", "DO702", "DQ531"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.80
      D_UDDTO:
        type: rand_date
        args:
          start: 2010
    linked_columns:
      V_RECNUM:
        type: choice
        file: Population
        linked_on: MOR_Fødsel_ID 

  t_sksopr:
    N: ${N}
    columns:
      C_OPR:
        type: choice
        args:
          options: ["KLDD10A", "KLDD10B", "KMAB00", "KMAB01", "KCKD05B"]
        corruptions:
          - type: insert_nan
            args:
              probability: 0.05
      D_ODTO:
        type: rand_date
      V_OTIME:
        type: rand_int
        args:
          min_val: 0
          max_val: 23
      V_OMINUT:
        type: rand_int
        args:
          min_val: 0
          max_val: 59
    linked_columns:
      V_RECNUM:
        type: choice
        file: Population
        linked_on: MOR_Fødsel_ID

  t_sksube:
    N: ${N}
    columns:
      C_OPR:
        type: choice
        args:
          options: ["AAF22", "ZZ0151"]
      C_OPRART:
        type: choice
        args:
          options: ["A", "B", "+"]
      C_TILOPR:
        type: choice
        args:
          options: ["BKHA1", "APBA1"]
        corruptions:
          - type: insert_missing
            args:
              probability: 0.25
      D_ODTO:
        type: rand_date
        args:
          start: 2010
      V_OTIME:
        type: rand_int
        args:
          min_val: 0
          max_val: 23
      V_OMINUT:
        type: rand_int
        args:
          min_val: 0
          max_val: 59
    linked_columns:
      V_RECNUM:
        type: choice
        file: Population
        linked_on: MOR_Fødsel_ID 