# @package _global_
defaults: 
  - ../root_config@
  - _self_

paths:
  output: ${oc.env:EHR2MEDS_DATA}/raw/fetal_data/SDS_AND_SP_from_population

N: 1000

data: 
  population:
    N: 1500
    columns:
      CPR_BARN:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      CPR_MOR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05

linked_data:
  mfr:
  # MFR2_main
    N: ${N}
    columns:
      ALDER_MODER:
        type: rand_int
        args:
          min_val: 18
          max_val: 45
      BMI_MODER:
        type: rand_float
        args:
          min_val: 18
          max_val: 40
      CPR_FADER:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      PK_MFR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      VAEGTE_MODER:
        type: rand_float
        args:
          min_val: 40
          max_val: 120
      PARITET:
        type: choice
        args:
          options: [1, 2, 3, 4]

      FOEDSELSDATO:
        type: rand_date
      GESTATIONSALDER_DAGE:
        type: rand_int
        args:
          min_val: 200
          max_val: 315
        corruptions:
          - type: insert_value
            args:
              new_value: "."
              probability: 0.05
      LEVENDE_ELLER_DOEDFOEDT:
        type: choice
        args:
          options: ["Levendefødt", "Dødfødt"]
      MARKOER_IGANGSAETTELSE:
        type: choice
        args:
          options: [1, ""]
      MARKOER_KEJSERSNIT:
        type: medical_code
        args:
          prefix: "KM"
        corruptions:
          - type: insert_value
            args:
              new_value: -1
              probability: 0.5
    linked_columns:
      CPR_BARN:
        type: choice_unique
        file: population
        linked_on: [CPR_BARN]
      CPR_MODER:
        type: choice
        file: population
        linked_on: [CPR_MOR]
        rename_to: [CPR_MODER]
      FOEDSELSLOEBENUMMER:
        type: choice
        file: population
        linked_on: [CPR_BARN]
        rename_to: [FOEDSELSLOEBENUMMER]

  nyfoedte:
  #MFR3
    N: ${N}
    columns:
      AntalDoedFoedte:
        type: choice
        args:
          options: [0, 1, 2]
      AntalLevendefoedte:
        type: choice
        args:
          options: [0, 1, 2]
      BMI_Mor:
        type: rand_float
        args:
          min_val: 18
          max_val: 40
      DW_EK_Nyfoedt:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      DW_EK_Foedsel:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      FoedselsDato_Barn:
        type: rand_date
      Gestationsalder:
        type: rand_int
        args:
          min_val: 200
          max_val: 315
        corruptions:
          - type: insert_value
            args:
              new_value: "."
              probability: 0.05
      Hoejde_Mor:
        type: rand_float
        args:
          min_val: 150
          max_val: 200
      Igangsaettelse_Ballonkateter:
        type: choice
        args:
          options: ["Nej", "Ja"]
      Igangsaettelse_HSP:
        type: choice
        args:
          options: ["Nej", "Ja"]
      Igangsaettelse_Medicinsk:
        type: choice
        args:
          options: ["Nej", "Ja"]
      Kejsersnit:
        type: medical_code
        args:
          prefix: "KM"
        corruptions:
          - type: insert_value
            args:
              new_value: -1
              probability: 0.5
      Laengde_Barn:
        type: rand_float
        args:
          min_val: 150
          max_val: 200
      LevendefoedtDoedfoedt:
        type: choice
        args:
          options: [1, 2]
      Paritet:
        type: choice
        args:
          options: [1, 2, 3, 4]
      Tobak_forbrug:
        type: medical_code
        corruptions:
          - type: insert_value
            args:
              new_value: -1
              probability: 0.05
      Vaegt_Mor:
        type: rand_float
        args:
          min_val: 40
          max_val: 120
      Vaegt_Barn:
        type: rand_float
        args:
          min_val: 40
          max_val: 120
    linked_columns:
      CPRnummer_Barn:
        type: choice_unique
        file: population
        linked_on: [CPR_BARN]
        rename_to: [CPRnummer_Barn]
      CPRnummer_Mor:
        type: choice
        file: population
        linked_on: [CPR_MOR]
        rename_to: [CPRnummer_Mor]
      DW_EK_Foedsel:
        type: choice
        file: population
        linked_on: [CPR_BARN]
        rename_to: [DW_EK_Foedsel]