# @package _global_
defaults: 
  - ../root_config@
  - _self_

paths:
  output: ${oc.env:EHR2MEDS_DATA}/raw/fetal_data/SDS_AND_SP_from_population

N: 1000
data: # Mangler DAR
  CPR_immigration:
    N: ${N}
    columns:
      V_PNR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
              forced_idx: [3]
      fodested_kode:
        type: rand_int
        args: 
          min_val: 0
          max_val: 900
  
  CPR_family:
    N: ${N}
    columns:
      v_pnr:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      v_mor_pnr:
        type: person_id
        corruptions:
          - type: insert_value
            args:
              new_value: "INVALID"
              probability: 0.05
      v_far_pnr:
        type: person_id
        corruptions:
          - type: insert_value
            args:
              new_value: "INVALID"
              probability: 0.05
      sosk:
        type: person_id
        corruptions:
          - type: insert_value
            args:
              new_value: "INVALID"
              probability: 0.05
      sosk_type:
        type: rand_int
        args:
          min_val: 1
          max_val: 5

  ivf_behandlingsforloeb: 
    N: ${N}
    columns:
      CPRnummer:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      Alder_behandlingsstart:
        type: rand_int
        args:
          min_val: 18
          max_val: 45
      Vaegt:
        type: rand_float
        args:
          min_val: 40
          max_val: 120
      Hoejde:
        type: rand_float
        args:
          min_val: 150
          max_val: 200
      Rygning_pr_dag: 
        type: rand_int
        args:
          min_val: 0
          max_val: 30
      Alkohol_pr_dag:
        type: rand_int
        args:
          min_val: 0
          max_val: 30
      Partner_vaegt:
        type: rand_float
        args:
          min_val: 40
          max_val: 120
      Partner_hoejde:
        type: rand_float
        args:
          min_val: 150
          max_val: 200

  lab_dm_forsker: # Could also add the lower and upper limits
    N: ${N}
    columns:
      PATIENT_CPR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
              forced_idx: [3]
      SAMPLINGDATE:
        type: rand_datetime
      SAMPLINGTIME:
        type: rand_time
      ANALYSISCODE:
        type: medical_code
        args:
          prefix: "NPU"
      UNIT:
        type: choice
        args:
          options: ["fl", "mmol/l", "10^9/l", "fmol", "U/L"]
      VALUE:
        type: mix_function
        args:
          functions:
            - type: rand_float 
              args:
                min_val: 0.001
                max_val: 100
            - type: rand_int
              args:
                min_val: 0
                max_val: 300
            - type: choice
              args:
                options: ["Positive", "Negative", "Ikke påvist", "påvist", "0 Rhd pos"]
          probabilities: [0.4, 0.4, 0.2]

  LPR2_ADM:  
    N: ${N}
    corruptions:
      - type: row_dropout
        args:
          probability: 0.05
          forced_idx: [5, 10]
    columns:
      person_id:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 4
              probability: 0.05
              forced_idx: [3]
      D_INDDATO: # start date
        type: rand_datetime
        args:
          start: 1977
      D_UDDDATO: # end date
        type: greater_than_datetime
        match:
          min_date: D_INDDATO
      C_ADIAG:
        type: medical_code
        args:
          prefix: "D"
      C_INDM: # urgency
        type: choice
        args:
          options: [1, 2]
      C_PATTYPE: # Patienttype
        type: choice
        args:
          options: [0, 1, 2, 3]
      C_SEX:
        type: choice
        args:
          options: ["M", "K"]
      K_RECNUM:
        type: rand_int
        args:
          min_val: 1
          max_val: 1000000000

  kontakter: 
  #LPR3
    N: ${N}
    corruptions:
      - type: row_dropout
        args:
          probability: 0.05
          forced_idx: [5, 10]
    columns:
      person_id:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 5
              probability: 0.05
              forced_idx: [3]
      aktionsdiagnose:
        type: medical_code
        args:
          prefix: "D"
      priority: # urgency
        type: choice
        args:
          options: [1, 2, 3]
      dato_start:
        type: rand_date
      tidspunkt_start:
        type: rand_time
      dato_slut:
        type: greater_than_date
        match:
          min_date: dato_start
      tidspunkt_slut:
        type: rand_time
      contact_id:
        type: rand_int
        args:
          min_val: 1
          max_val: 600000
      forloeb_id: 
        type: rand_int
        args:
          min_val: 1
          max_val: 600000

  epikur:
  #LSR
    N: ${N}
    columns:
      cpr:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      eksd:
        type: rand_datetime
        args:
          start: 2000
      ATC:
        type: medical_code
        args:
          prefix: ""
      vnr:
        type: rand_int
        args:
          min_val: 100000
          max_val: 999999

  SSR_GP:
  # Dont know what this is on NGC
    N: ${N}
    columns:
      CPR:
        type: person_id
        corruptions:
          - type: truncation
            args:
              max_length: 10
              probability: 0.05
      Date:
        type: rand_datetime
      Ydelse:
        type: rand_int
        args:
          min_val: 1
          max_val: 5000
      Honuge:
        type: rand_int
        args:
          min_val: 1
          max_val: 52

linked_data: # Data that needs to be linked to the data above
  amning_afl:
  #BDB
    N: ${N}
    linked_columns:
      CPR:
        type: choice
        file: population
        linked_on: [CPR_BARN]
    columns:
      BIRTHDATE:
        type: rand_datetime
        args:
          start: 2000
      VARIGHED_DAGE:
        type: rand_int
        args:
          min_val: 0
          max_val: 200
  
  maalinger_afl:
  #BDB
    N: ${N}
    linked_columns:
      CPR:
        type: choice
        file: population
        linked_on: [CPR_BARN]
    columns:
      BIRTHDATE:
        type: rand_datetime
        args:
          start: 2000
      MEASUREMENTDATE:
        type: rand_datetime
        args:
          start: 2000
      #MEASUREMENT_TIME:
      #  type: greater_than_datetime
      #  match:
      #    min_date: MEASUREMENT_DATE
      HEIGHT:
        type: rand_float
        args:
          min_val: 50
          max_val: 180
      WEIGHT:
        type: rand_int
        args:
          min_val: 2500
          max_val: 70000
  diagnoser:
  #LPR3
    N: ${N}
    columns:
      diagnosekode:
        type: medical_code
        args:
          prefix: "D"
      diagnose_type:
        type: choice
        args:
          options: ["A", "B", "+"]

    linked_columns:
      contact_id: 
        type: choice
        file: LPR3_kontakter
        linked_on: [contact_id]
        rename_to: [contact_id_new]
    
  procedurer_kirurgi:
  #LPR3
    N: ${N}
    columns:
      procedurekode:
        type: medical_code
        args:
          prefix: "K"
      proceduretype:
        type: choice
        args:
          options: ["P", "+"]
    linked_columns:
      contact_id: 
        type: choice
        file: LPR3_kontakter
        linked_on: [contact_id]
        rename_to: [contact_id_new]

  LPR2_procedures:
    N: ${N}
    columns:
      C_TILOPR:
        type: medical_code
        args:
          prefix: ""
      D_ODTO:
        type: rand_date
    linked_columns:
      key_id: 
        type: choice
        file: LPR2_ADM
        linked_on: [K_RECNUM]
        rename_to: [V_RECNUM]
  
  LPR2_diagnosis:
    N: ${N}
    columns:
      C_DIAG:
        type: medical_code
        args:
          prefix: "D"
      C_DIAGTYPE:
        type: choice
        args:
          options: ["A", "B", "+"]
    linked_columns:
      key_id: 
        type: choice
        file: LPR2_ADM
        linked_on: [K_RECNUM]
        rename_to: [V_RECNUM]
  
  LPR2_hosp_admissions:
    N: ${N}
    columns:
      D_AMBDTO:
        type: rand_datetime
    linked_columns:
      key_id: 
        type: choice
        file: LPR2_ADM
        linked_on: [K_RECNUM]
        rename_to: [V_RECNUM]
  
  infektioner:
  #MFR2
    N: ${N}
    columns:
      SKSKODE:
        type: medical_code
        args:
          prefix: "D"
      KODETYPE:
        type: choice
        args:
          options: ["A", "B", "+"]
    linked_columns:
      PK_MFR:
        type: choice
        file: mfr
        linked_on: [PK_MFR]
        rename_to: [FK_MFR]
  
  blodmaengde:
  #MFR2
    N: ${N}
    columns:
      SKSKODE:
        type: medical_code
        args:
          prefix: "D"
      KODETYPE:
        type: choice
        args:
          options: ["A", "B", "+"]
      BLOOD_LOSS:
        type: rand_int
        args:
          min_val: 100
          max_val: 2000
        corruptions:
          - type: insert_value
            args:
              new_value: "."
              probability: 0.8
    linked_columns:
      PK_MFR:
        type: choice
        file: mfr
        linked_on: [PK_MFR]
        rename_to: [FK_MFR]

  barn_kontakter:
  #MFR3 
    N: ${N}
    columns:
      Aktionsdiagnose:
        type: medical_code
        args:
          prefix: "D"
      Priority:
        type: choice
        args:
          options: [1, 2, 3]
      Datostart:
        type: rand_date
      Tidspunktstart:
        type: rand_time
      Datoslut:
        type: greater_than_date
        match:
          min_date: Datostart
      Tidspunktslut:
        type: rand_time
      contact_id:
        type: rand_int
        args:
          min_val: 1
          max_val: 600000
    
    linked_columns:
      birth_id:
        type: choice
        file: MFR3_nyfoedte
        linked_on: [birth_id]

  patient_info:
    N: ${N}
    linked_columns:
      CPR:
        type: choice
        file: population
        linked_on: [CPR_BARN]
        rename_to: [CPR]

    columns:
      Birthdate:
        type: rand_date
      Deathdate:
        type: greater_than_date
        match:
          min_date: Birthdate
        corruptions:
          - type: insert_nan
            args:
              probability: 0.8
      Gender:
        type: choice
        args:
          options: ["M", "K"]
      Ethnicity:
        type: choice
        args:
          options: ["Unspecified", "Nordeuropa", "Asien", "Mellemøsten"]
