subject_id_col: subject_id

patients_info:
  dob:
    code: "DOB"
    time: $Birthdate as "%Y-%m-%d"
  dod:
    code: "DOD"
    time: $Deathdate as "%Y-%m-%d"
  gender:
    code: f"GENDER//{$gender}"
    time: null
    
diagnosis:
  diagnosis:
    code: f"D//{$Diagnosekode}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"

procedure:
  procedure:
    code: f"P//{$Procedurekode}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"

labtest:
  labtest:
    code: f"LAB//{$BestOrd}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"
    lab_value: $numeric_value

admissions:
  IN:
    code: f"IN//{$Afsnit}"
    time: $timestamp_in as "%Y-%m-%d"
  OUT:
    code: f"OUT//{$Afsnit}"
    time: $timestamp_out as "%Y-%m-%d"
