subject_id_col: subject_id

subject:
  subject_id_col: subject_id
  dob:
    code: 
      - DOB
    time: col(birthdate)
    time_format: "%Y-%m-%d"
  dod:
    code: 
      - DOD
    time: col(deathdate)
    time_format: "%Y-%m-%d"
  gender:
    code:
      - "GENDER"
      - col(gender)
    time: null    
    
diagnosis:
  diagnosis:
    code:
      - "D"
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"

procedure:
  procedure:
    code:
      - "P"
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"

labtest:
  labtest:
    code:
      - "LAB"
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"
    numeric_value: col(numeric_value)

admissions:
  admissions:
    code:
      - "A"
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"
