# Map different spellings of a common concept into one token.
value_map:
  NEG: NEGATIVE
  NEGATIV: NEGATIVE
  NEGATIVE: NEGATIVE
  POS: POSITIVE
  POSITIV: POSITIVE
  POSITIVE: POSITIVE
  PÅVIST: DETECTED
  PÏ¿½VIST: DETECTED
  IKKE PÅVIST: NOT_DETECTED
  IKKE PÏ¿½VIST: NOT_DETECTED
  EJ PÅVIST: NOT_DETECTED
  EJ PÏ¿½VIST: NOT_DETECTED
  NORMAL: NORMAL
  NORMALT: NORMAL
  0 RHD POS: O RHD POS
  0 RHD NEG: O RHD NEG

namespace: LABTEST
separator: "//"
