subject_id_col: subject_id

patients_info:
  subject_id_col: subject_id
  dob:
    code: "DOB"
    time: $birthdate as "%Y-%m-%d"
  dod:
    code: "DOD"
    time: $deathdate as "%Y-%m-%d"
  gender:
    code: $gender
    time:
    
diagnosis:
  diagnosis:
    code: f"D//{$code}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"

procedure:
  procedure:
    code: f"P//{$code}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"

labtest:
  labtest:
    code: f"LAB//{$code}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"
    lab_value: $numeric_value

admissions:
  admissions:
    code: f"A//{$code}"
    time: $timestamp as "%Y-%m-%d %H:%M:%S%.f"
