subject_id_col: subject_id

LPR3_kontakter:
  aktionsdiagnose:
    code: f"DIAG//{$aktionsdiagnose}"
    time: $dato_start # as "%Y-%m-%d"
  priority:
    code: f"PRIORITY//{$priority}"
    time: set_time($dato_start, $tidspunkt_start)