subject_id_col: subject_id

# Patient demographics (patients_info)
patients_info:
  subject_id_col: subject_id
  dob:
    code:
      - DOB
    time: col(birthdate)
    time_format: "%Y-%m-%d %H:%M:%S.%f"
  dod:
    code:
      - DOD
    time: col(deathdate)
    time_format: "%Y-%m-%d %H:%M:%S.%f"
  gender:
    code:
      - GENDER
      - col(gender)
    time: null

admissions:
  admissions:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"

diagnosis:
  diagnosis:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"

procedure:
  procedure:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"

medication:
  medication:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"

labtest:
  labtest:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"
    numeric_value: col(numeric_value)

smoking_info:
  smoking_info:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"

alcohol_info:
  alcohol_info:
    code:
      - col(code)
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S.%f"