subject_id_col: subject_id

# Patient demographics
subject:
  subject_id_col: subject_id
  dob:
    code:
      - DOB
    time: col(birthdate)
    time_format: "%Y-%m-%d"
  dod:
    code:
      - DOD
    time: col(deathdate)
    time_format: "%Y-%m-%d"
  gender:
    code:
      - GENDER
      - col(gender)
    time: null

# Pathology 
SDS_dimpatologiskdiagnose:
  SDS_dimpatologiskdiagnose:
    code: f"PAT//{$code}"
    time: col(timestamp)
    time_format: "%Y-%m-%dT%H:%M:%S"

# LPR3 diagnoses
SDS_diagnoser:
  SDS_diagnoser:
    code: f"RD//{$code}"
    time: set_time($date_end as '%Y-%m-%d', $time_end as '%H:%M:%S')

# LPR diagnoses 
SDS_t_diag:
  SDS_t_diag:
    code: f"RD//{$code}"
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"

# LPR3 contacts 
SDS_kontakter:
  SDS_kontakter:
    code: f"RC//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')

# LPR admissions 
SDS_t_adm:
  SDS_t_adm:
    code: f"RC_ADM//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $v_indtime as '%H', $v_indminut as '%M')

# LPR surgical procedures 
SDS_t_sksopr:
  SDS_t_sksopr:
    code: f"RPS//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $v_otime as '%H', $v_ominut as '%M')

# LPR other procedures 
SDS_t_sksube:
  SDS_t_sksube:
    code: f"RPO//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $v_otime as '%H', $v_ominut as '%M')

# LPR3 surgical procedures 
SDS_procedurer_kirurgi:
  SDS_procedurer_kirurgi:
    code: f"RPS//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')

# LPR3 other procedures
SDS_procedurer_andre:
  SDS_procedurer_andre:
    code: f"RPO//{$code}"
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')

# Medication (NOTE; can be safely replaced with epikur)
SDS_ekokur:
  SDS_ekokur:
    code: f"RM//{$code}"
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"

# Administered medication 
SDS_indberetningmedpris:
  SDS_indberetningmedpris:
    code: f"RMA//{$code}"
    time: col(timestamp)
    time_format: "%Y-%m-%d %H:%M:%S"

# NOTE: numeric_value is NOT normalized here - needs to adhere to splits to not have information leakage
SDS_laboratorieproevesvar:
  SDS_laboratorieproevesvar:
    code: f"L//{$code}"
    time: set_time($samplingdate as '%Y-%m-%d', $samplingtime as '%H:%M:%S')
    numeric_value: col(numeric_value)