subject_id_col: subject_id

# Patient demographics
patients_info:
  dob:
    code: "DOB"
    time: $birthdate as "%Y-%m-%d"
  dod:
    code: "DOD"
    time: $deathdate as "%Y-%m-%d"
  gender:
    code: '"GENDER//"+$gender'
    time: null

# Pathology 
SDS_dimpatologiskdiagnose:
  SDS_dimpatologiskdiagnose:
    code: '"PAT//"+$diagnose_snomed_kode'
    time: coalesce($timestamp as '%Y-%m-%dT%H:%M:%S', $timestamp_fallback as '%Y-%m-%dT%H:%M:%S')
    source_row_id: "$source_row_id"

# LPR3 diagnoses
SDS_diagnoser:
  SDS_diagnoser:
    code: '"RD//"+$diagnosekode'
    time: set_time($date_end as '%Y-%m-%d', $time_end as '%H:%M:%S')
    source_row_id: "$source_row_id"
  diagnose_type:
    code: '"RD_TYPE//"+$diagnosetype'
    time: set_time($date_end as '%Y-%m-%d', $time_end as '%H:%M:%S')
    source_row_id: "$source_row_id"

# LPR diagnoses 
SDS_t_diag:
  diag:
    code: '"RD//"+$c_diag'
    time: $timestamp as "%Y-%m-%d %H:%M:%S"
    source_row_id: "$source_row_id"
  diag_type:
    code: '"RD_TYPE//"+$c_diagtype'
    time: $timestamp as "%Y-%m-%d %H:%M:%S"
    source_row_id: "$source_row_id"
  tildiag:
    code: '"RD//"+$c_tildiag'
    time: $timestamp as "%Y-%m-%d %H:%M:%S"
    source_row_id: "$source_row_id"

# LPR3 contacts 
SDS_kontakter:
  SDS_kontakter:
    code: '"RC//"+$aktionsdiagnose'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"
  contact_reason:
    code: '"RC_REASON//"+$kontaktaarsag'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"
  priority:
    code: '"RC_PRIO//"+$prioritet'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"
  contact_type:
    code: '"RC_TYPE//"+$kontakttype'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"
  clinical_specialty:
    code: '"RC_SPEC//"+$hovedspeciale_ans'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"
  region_code:
    code: '"RC_REG//"+$region_ans'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"

# LPR admissions 
SDS_t_adm:
  SDS_t_adm:
    code: '"RC_ADM//"+$c_adiag'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')
    source_row_id: "$source_row_id"
  contact_reason:
    code: '"RC_REASON//"+$c_kontaars'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')
    source_row_id: "$source_row_id"
  patient_type:
    code: '"RC_ADM_TYPE//"+$c_pattype'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d') 
    source_row_id: "$source_row_id"
  priority:
    code: '"RC_PRIO//"+$priority'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')  
    source_row_id: "$source_row_id"
  clinical_specialty:
    code: '"RC_SPEC//"+$c_spec'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d') 
    source_row_id: "$source_row_id"
  region_code:  
    code: '"RC_REG//"+$c_sgh'
    time: coalesce(set_time($date_start as '%Y-%m-%d',((($v_indtime as int) as str) + ":" + (($v_indminut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')
    source_row_id: "$source_row_id"
# LPR surgical procedures 
SDS_t_sksopr:
  SDS_t_sksopr:
    code: '"RPS//"+$c_opr'
    time: coalesce(set_time($date_start as '%Y-%m-%d', ((($v_otime as int) as str) + ":" + (($v_ominut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')
    source_row_id: "$source_row_id"

# LPR other procedures 
SDS_t_sksube:
  SDS_t_sksube:
    code: '"RPO//"+$c_opr'
    time: coalesce(set_time($date_start as '%Y-%m-%d', ((($v_otime as int) as str) + ":" + (($v_ominut as int) as str)) as '%H:%M'), $date_start as '%Y-%m-%d')
    source_row_id: "$source_row_id"

# LPR3 surgical procedures 
SDS_procedurer_kirurgi:
  SDS_procedurer_kirurgi:
    code: '"RPS//"+$procedurekode'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"

# LPR3 other procedures
SDS_procedurer_andre:
  SDS_procedurer_andre:
    code: '"RPO//"+$procedurekode'
    time: set_time($date_start as '%Y-%m-%d', $time_start as '%H:%M:%S')
    source_row_id: "$source_row_id"

# Medication (NOTE; can be safely replaced with epikur)
SDS_ekokur:
  SDS_ekokur:
    code: '"RM//"+$atc'
    time: $timestamp
    source_row_id: "$source_row_id"

# Administered medication 
SDS_indberetningmedpris:
  SDS_indberetningmedpris:
    code: '"RMA//"+$c_atc'
    time: $timestamp
    source_row_id: "$source_row_id"
  patient_type:
    code: '"RMA_PAT_TYPE//"+$c_patienttype'
    time: $timestamp
    source_row_id: "$source_row_id"

# NOTE: numeric_value is NOT normalized here - needs to adhere to splits to not have information leakage
# Inclusion of text_value to allow for non-numerics.
SDS_laboratorieproevesvar:
  SDS_laboratorieproevesvar:
    code: '"L//"+$analysiscode'
    time: set_time($samplingdate as '%Y-%m-%d', $samplingtime as '%H:%M:%S%.f')
    numeric_value: '(extract group 1 of /^\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)\s*$/ from $samplevalue) as float64'
    text_value: "$samplevalue"
    source_row_id: "$source_row_id"