subject_id_col: subject_id

# Patient demographics
patients_info:
  dob:
    code: "DOB"
    time: $birthdate
  dod:
    code: "DOD"
    time: $deathdate
  gender:
    code: f"GENDER//{$gender}"
    time: null

# Pathology 
SDS_dimpatologiskdiagnose:
  SDS_dimpatologiskdiagnose:
    code: f"PAT//{$diagnose_snomed_kode}"
    time: coalesce($timestamp as '%Y-%m-%dT%H:%M:%S', ($timestamp_fallback as '%Y-%m-%d') as datetime)

# LPR3 diagnoses
SDS_diagnoser:
  SDS_diagnoser:
    code: f"RD//{$diagnosekode}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  diagnose_type:
    code: f"RD_TYPE//{$diagnosetype}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')

# LPR diagnoses 
SDS_t_diag:
  diag:
    code: f"RD//{$c_diag}"
    time: set_time($date_start, f"{($hour_start as int)}:{($minute_start as int)}" as '%H:%M')
  diag_type:
    code: f"RD_TYPE//{$c_diagtype}"
    time: set_time($date_start, f"{($hour_start as int)}:{($minute_start as int)}" as '%H:%M')
  tildiag:
    code: f"RD//{$c_tildiag}"
    time: set_time($date_start, f"{($hour_start as int)}:{($minute_start as int)}" as '%H:%M')

# LPR3 contacts 
SDS_kontakter:
  SDS_kontakter:
    code: f"RC//{$aktionsdiagnose}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  contact_reason:
    code: f"RC_REASON//{$kontaktaarsag}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  priority:
    code: f"RC_PRIO//{$prioritet}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  contact_type:
    code: f"RC_TYPE//{$kontakttype}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  clinical_specialty:
    code: f"RC_SPEC//{$hovedspeciale_ans}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  region_code:
    code: f"RC_REG//{$region_ans}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')

# LPR admissions 
SDS_t_adm:
  SDS_t_adm:
    code: f"RC_ADM//{$c_adiag}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')
  contact_reason:
    code: f"RC_REASON//{$c_kontaars}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')
  patient_type:
    code: f"RC_ADM_TYPE//{$c_pattype}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')
  priority:
    code: f"RC_PRIO//{$priority}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')
  clinical_specialty:
    code: f"RC_SPEC//{$c_spec}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')
  region_code:
    code: f"RC_REG//{$c_sgh}"
    time: set_time($date_start, f"{($v_indtime as int)}:{($v_indminut as int)}" as '%H:%M')

# LPR surgical procedures 
SDS_t_sksopr:
  SDS_t_sksopr:
    code: f"RPS//{$c_opr}"
    time: set_time($date_start, f"{(($v_otime as float) as int)}:{(($v_ominut as float) as int)}" as '%H:%M')

# LPR other procedures 
SDS_t_sksube:
  SDS_t_sksube:
    code: f"RPO//{$c_opr}"
    time: set_time($date_start, f"{(($v_otime as float) as int)}:{(($v_ominut as float) as int)}" as '%H:%M')
  procedure_type:
    code: f"RPO_TYPE//{coalesce($c_oprart, "P")}" # NOTE: default to "P" if missing, as this is LPR3 behavior
    time: set_time($date_start, f"{(($v_otime as float) as int)}:{(($v_ominut as float) as int)}" as '%H:%M')

# LPR3 surgical procedures 
SDS_procedurer_kirurgi:
  SDS_procedurer_kirurgi:
    code: f"RPS//{$procedurekode}"
    time: set_time($date_start, $time_start)

# LPR3 other procedures
SDS_procedurer_andre:
  SDS_procedurer_andre:
    code: f"RPO//{$procedurekode}"
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')
  procedure_type:
    code: f"RPO_TYPE//{$proceduretype}" # NOTE: default to "P" if missing, as this is LPR3 behavior
    time: set_time($date_start, $time_start as '%H:%M:%S%.f')

# Medication (NOTE; can be safely replaced with epikur)
SDS_ekokur:
  SDS_ekokur:
    code: f"RM//{$atc}"
    time: $timestamp

# Administered medication 
SDS_indberetningmedpris:
  SDS_indberetningmedpris:
    code: f"RMA//{$c_atc}"
    time: $timestamp
  patient_type:
    code: f"RMA_PAT_TYPE//{$c_patienttype}"
    time: $timestamp

# Keep numeric_value raw here. Split-aware normalization and binning should be
# performed later by aggregate_numeric_metadata and annotate_numeric_values.
SDS_laboratorieproevesvar:
  SDS_laboratorieproevesvar:
    code: f"L//{$analysiscode}"
    time: set_time($samplingdate as '%Y-%m-%d', $samplingtime as '%H:%M:%S%.f') # sampling time had SQL precision, which is the reason for added x.f
    numeric_value: '(extract group 1 of /^\s*([-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?)\s*$/ from $samplevalue) as float64'  # Regex to extract numeric value from string, allowing for scientific notation and whitespace
    text_value: "$samplevalue" # the value as string, for cases where the value is not numeric (e.g., "NEG", "POS", "<0.1", etc.). Duplicates where text and numeric are the same are dropped.
