subject_id_col: subject_id

central_patient:
  dob:
    code: "DOB"
    time: $birthdate
  dod:
    code: "DOD"
    time: $deathdate
  sex:
    code: f"SEX//{$sex}"
    time: null

epikur:
  epikur:
    code: f"MEDICATION//{$atc}"
    time: $start_timestamp

indberetningmedpris:
  indberetningmedpris:
    code: f"MEDICATION//{$c_atc}"
    time: coalesce($start_timestamp, $end_timestamp)

t_diag:
  t_diag:
    code: f"DIAGNOSIS//{$c_diag}"
    time: coalesce($end_timestamp, $start_timestamp)

diagnoser:
  diagnoser:
    code: f"DIAGNOSIS//{$diagnosekode}"
    time: coalesce($end_timestamp, $start_timestamp)

t_psyk_diag:
  t_psyk_diag:
    code: f"DIAGNOSIS//{$c_diag}"
    time: coalesce($end_timestamp, $start_timestamp)
  
t_sksopr:
  t_sksopr:
    code: f"PROCEDURE//{$c_opr}"
    time: $start_timestamp

t_sksube:
  t_sksube:
    code: f"PROCEDURE//{$c_opr}"
    time: $start_timestamp

t_psyk_sksopr:
  t_psyk_sksopr:
    code: f"PROCEDURE//{$c_opr}"
    time: $start_timestamp

t_psyk_sksube:
  t_psyk_sksube:
    code: f"PROCEDURE//{$c_opr}"
    time: $start_timestamp

procedurer_andre:
  procedurer_andre:
    code: f"PROCEDURE//{$procedurekode}"
    time: coalesce($start_timestamp, $end_timestamp)

procedurer_kirurgi:
  procedurer_kirurgi:
    code: f"PROCEDURE//{$procedurekode}"
    time: coalesce($start_timestamp, $end_timestamp)
