defaults:
  - _extract
  - _self_

description: |-
  This pipeline extracts the preMEDS dataset in longitudinal, sparse form from an input dataset meeting
  select criteria and converts them to the flattened MEDS format. You can control the key arguments to this
  pipeline by setting environment variables:

  export EVENT_CONVERSION_CONFIG_FP=event_configs.yaml       # Path to your event conversion config
  export PREMEDS_INPUT_DIR=../preMEDS_w_meta                 # Path to the output dir of the pre-MEDS step
  export PREMEDS_MEDS_COHORT_DIR=../MEDS_new_data            # Path to where you want the dataset to live

event_conversion_config_fp: ${oc.env:EVENT_CONVERSION_CONFIG_FP}

input_dir: ${oc.env:PREMEDS_INPUT_DIR}
cohort_dir: ${oc.env:PREMEDS_MEDS_COHORT_DIR}

etl_metadata:
  dataset_name: preMEDS
  dataset_version: 1.0

stage_configs:
  shard_events:
    infer_schema_length: 999999999

stages:
  - shard_events
  - split_and_shard_subjects
  - convert_to_sharded_events
  - merge_to_MEDS_cohort
  - extract_code_metadata
  - finalize_MEDS_metadata
  - finalize_MEDS_data
