test: true
env: azure
run_name: MEDS
chunksize: 500_000
paths:
  output_dir: outputs/preMEDS
  file_type: csv 

data_path:
  concepts:
    datastore: researcher_data
    dump_path: 'data-backup/SP-dumps/2024-09-10'
  register_concepts:
    datastore: researcher_data
    dump_path: 'FSEID'
  pid_link: 
    datastore: researcher_data
    dump_path: 'maskerede_data'
    filename: mapping.csv
    join_col: PID
    target_col: CPR_hash

concepts:
  admissions:
    filename: CPMI_ADTHaendelser.parquet
    # columns to keep, rename, and the final names
    rename_columns:
      CPR_hash: subject_id
      Flyt_ind: timestamp_in
      Flyt_ud: timestamp_out
      Afsnit: section
      ADT_haendelse: type
    use_adm_move: false

  diagnosis:
    filename: CPMI_Diagnoser.parquet
    rename_columns:
      Diagnosekode: code
      Diagnose: fill_code
      Noteret_dato: timestamp
      CPR_hash: subject_id
    fillna:
      code:
        column: fill_code
        regex: '\((D[^)]+)\)'
    code_prefix: "D_"

  procedure:
    filename: CPMI_Procedurer.parquet
    rename_columns:
      ProcedureCode: code
      ProcedureName: fill_code
      ServiceDatetime: timestamp
      ServiceDate: fill_timestamp
      CPR_hash: subject_id
    fillna:
      code:
        column: fill_code
      timestamp:
        column: fill_timestamp
    code_prefix: "P_"

  medication:
    filename: CPMI_Medicin.parquet
    rename_columns:
      ATC: code
      Administrationstidspunkt: timestamp
      Bestillingsdato: fill_timestamp
      CPR_hash: subject_id
    fillna:
      timestamp:
        column: fill_timestamp
    code_prefix: "M_"

  labtest:
    filename: CPMI_Labsvar.parquet
    rename_columns:
      BestOrd: code
      Prøvetagningstidspunkt: timestamp
      Bestillingsdato: fill_timestamp
      Resultatværdi: numeric_value
      CPR_hash: subject_id
    fillna:
      timestamp:
        column: fill_timestamp
    code_prefix: "L_"
    numeric_columns: [numeric_value]

register_concepts:
  register_diagnosis:
    filename: diagnoser.asc
    rename_columns:
      diagnosekode: code
      diagnosetype: code_type
      dw_ek_kontakt: contact_id

    code_prefix: "RD_"
    mappings:
      - source_column: contact_id
        via_file: kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: PID
        rename_to: subject_id
      - source_column: contact_id
        via_file: kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: dato_slut
        rename_to: timestamp
        drop_source: true

  register_contacts:
    filename: kontakter.parquet
    rename_columns:
      PID: subject_id
      dato_start: date_start
      tidspunkt_start: time_start
      aktionsdiagnose: code
      kontaktaarsag: contact_reason
      hovedspeciale_ans: clinical_specialty
      region_ans: region_code

    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true

    unroll_columns:
      - column: contact_reason
        prefix: "RC_REASON_"
      - column: clinical_specialty
        prefix: "RC_SPEC_"
      - column: region_code
        prefix: "RC_REG_"
    code_prefix: "RC_"

  register_medication:
    filename: epikur.parquet
    rename_columns:
      PID: subject_id
      vnr: vnr_code
      eksd: timestamp
    mappings:
      - source_column: vnr_code
        how: left
        via_file: laegemiddeloplysninger.asc
        join_on: VNR
        target_column: PNAME
        rename_to: code
        drop_source: false
    code_prefix: "RM_"

  register_procedures_surgery:
    filename: procedurer_kirurgi.asc
    rename_columns:
      procedurekode: code
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPS_"
    mappings:
      - source_column: contact_id
        via_file: kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: PID
        rename_to: subject_id
        drop_source: true
    
  register_procedures_other:
    filename: procedurer_andre.asc
    rename_columns:
      procedurekode: code
      proceduretype: procedure_type
      dato_start: date_start
      tidspunkt_start: time_start
      dw_ek_kontakt: contact_id
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPO_"
    mappings:
      - source_column: contact_id
        via_file: kontakter.parquet
        join_on: dw_ek_kontakt
        target_column: PID
        rename_to: subject_id
        drop_source: true

patients_info:
  filename: CPMI_PatientInfo.parquet
  rename_columns:
    CPR_hash: subject_id
    Fødselsdato: birthdate
    Dødsdato: deathdate
    Køn: gender
  file_type: parquet