test: false
env: local
run_name: normalise_labs
paths:
  input: outputs/preMEDS/labtest.csv
  output_dir: outputs/preMEDS

file_name: labtest_norm_min_max.csv
  

data:
  norm_type: Min_max
  chunksize: 30000000
  test_rows: 1000000
  dist_path: null  # Optional path to distribution data
