paths:
  main_folder: C:/Users/fjn197/PhD/projects/PHAIR/pipelines/synthea/output/synthea500/csv
  output_dir: formatted_data/synthea500_test
  file_type: csv

preprocessor:
  _target_: __main__.mimic.AzurePreprocessor
  _recursive_: false

concepts:
  diagnosis:
    filename: CPMI_Diagnoser.parquet
    names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT,]
    usecols: [0, 2, 3, 4]
    dtypes: {CONCEPT: category}

  medication:
    filename: CPMI_Medicin.parquet
    names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT]
    usecols: [0, 2, 4, 5]
    dtypes: {CONCEPT: category}  

admissions:
    filename: CPMI_ADTHaendelser.parquet
    names: [TIMESTAMP, PID, ADMISSION_ID, CONCEPT]
    usecols: [0, 2, 4, 5]

patients_info:
    filename: CPMI_PatientInfo.parquet
    names: [PID, BIRTHDATE, DEATHDATE, GENDER]
    usecols: [0, 1, 2, 3]