paths:
  raw_data_dir: C:\Users\fjn197\PhD\projects\PHAIR\pipelines\ehr_preprocess\data\raw\mimic-iii-clinical-database-1.4
  working_data_dir: C:\Users\fjn197\PhD\projects\PHAIR\pipelines\ehr_preprocess\data\
  save_name: null
processing:
  _target_: __main__.preprocessors.MimicIII 
  _recursive_: false
convert_csv_to_parquet: true

   