preprocessor:
  _target_: preprocessors.mimic4.MIMIC4Preprocessor
  _recursive_: false
paths:
  main_folder: ../data/raw/mimic-iv-2.2/mimic-iv-2.2
  output_dir: ../data/formatted/mimic4_med_diag
  file_type: csv

test: True

concepts:
  diagnose:
    icd:
      filename: hosp/diagnoses_icd.csv.gz
      names: [PID, ADMISSION_ID, CONCEPT, icd_version]
      usecols: [0, 1, 3, 4]
      dtype: {ADMISSION_ID: int}
      converters:
        CONCEPT:
          _partial_: true
          _target_: preprocessors.utils.prepend
          prepend_token: D
      function:
        _partial_: true
        _target_: preprocessors.mimic4.MIMIC4Preprocessor.map_icd9_to_icd10
      combine: 
          method: merge
          on: ADMISSION_ID

    admissions:
      filename: hosp/admissions.csv.gz
      names: [ADMISSION_ID, TIMESTAMP]
      usecols: [1, 3]
      parse_dates: [TIMESTAMP]
      dtype: {ADMISSION_ID: int}

  medication:
    mecication:
      filename: hosp/prescriptions.csv.gz
      names: [PID, ADMISSION_ID, TIMESTAMP, drug, CONCEPT]
      usecols: [0, 1, 6, 9, 12]
      parse_dates: [TIMESTAMP]
      dtype: {CONCEPT: category}
      function: 
        _partial_: true
        _target_: preprocessors.mimic4.MIMIC4Preprocessor.handle_medication
        prepend: M
      

patients_info:
  basic_info:
    filename: hosp/patients.csv.gz
    usecols: [0, 1, 2, 3, 5]
    names: [PID, GENDER, anchor_age, anchor_year, DATE_OF_DEATH]
    parse_dates: [DATE_OF_DEATH]
    function:
      _partial_: true
      _target_: preprocessors.mimic4.MIMIC4Preprocessor.calculate_birthdate

  admission_info:
    filename: hosp/admissions.csv.gz
    usecols: [0, 9, 10, 11, 12]
    names: [PID, INSURANCE, LANGUAGE,  MARITALSTATUS, RACE]
    function: 
      _partial_: true
      _target_: preprocessors.mimic4.MIMIC4Preprocessor.majority_vote