pid: &pid subject_id 
time: &time time
code: &code code
admission: &admission ADMISSION_ID
dob: &dob DOB
dod: &dod DOD

numerical_value: &numerical_value numerical_value
paths:
  main_folder: ../example_data/parquet_synthea500
  output_dir: ../data/formatted/synthea_meds500
  file_type: csv

preprocessor:
  _target_: ehr_preprocess.preprocessors.synthea_meds.MEDSPreprocessor
  _recursive_: false
  chunk_size: 100

pids:
  filename: patients.parquet
  col: Id
concepts:
  diagnose:
    snomed:
      filename: conditions.parquet
      usecols: [START, PATIENT, ENCOUNTER, CODE]
      names: [*time, *pid, *admission, *code]
      

  medication:
    administered:
      filename: medications.parquet
      usecols: [START, PATIENT, ENCOUNTER, CODE, DISPENSES]
      names: [*time, *pid, *admission, *code, *numerical_value]
      

admissions:
  admission:
    filename: medications.parquet
    usecols: [START, PATIENT, ENCOUNTER]
    names: [*time, *pid, *admission]
    
patients_info:
  all:
    filename: patients.parquet
    usecols: [Id, BIRTHDATE, DEATHDATE, ETHNICITY, GENDER]
    names: [*pid, *dob, *dod, ETHNICITY, GENDER]
    
      