# @package _global_
defaults: 
  - ../root_config@
  - _self_

logging:
  level: INFO
  path: ./outputs/logs

test: false
env: local
run_name: normalise_labs
paths:
  input: ${oc.env:EHR2MEDS_DATA}/MEDS/SP/
  output: ${oc.env:EHR2MEDS_DATA}/MEDS/SP/normalized_data
  dist_path: #null  # Optional path to distribution data

file_name: labtest
  
data:
  norm_type: min_max
  chunksize: 30000000
  numeric_value: numeric_value
  build_distribution_on: ["train", "tuning"]