test: false
env: azure
run_name: MEDS
paths:
  output_dir: outputs/preMEDS
  file_type: csv 

preprocessor:
  _target_: preprocessors.preMEDS.MEDSPreprocessor

data_path:
  concepts:
    datastore: researcher_data
    dump_path: 'data-backup/SP-dumps/2024-09-10'
  register_concepts:
    datastore: researcher_data
    dump_path: 'FSEID'
  mapping: # maps from register PIDs to sp hashes
    datastore: researcher_data
    dump_path: 'maskerede_data'

concepts:
  admissions:
    filename: CPMI_ADTHaendelser.parquet
    # columns to keep, rename, and the final names
    columns_map:
      CPR_hash: subject_id
      Flyt_ind: admission
      Flyt_ud: discharge
      # Afsnit: section 
      # ADT_haendelse: type
    # some special post-processing function for merges
    postprocess: "merge_admissions"

  diagnosis:
    filename: CPMI_Diagnoser.parquet
    columns_map:
      Diagnosekode: code
      Diagnose: fill_code
      Noteret_dato: timestamp
      CPR_hash: subject_id
    fillna:
      code:
        column: fill_code
        regex: '\((D[^)]+)\)'
    code_prefix: "D_"

  procedure:
    filename: CPMI_Procedurer.parquet
    columns_map:
      ProcedureCode: code
      ProcedureName: fill_code
      ServiceDatetime: timestamp
      ServiceDate: fill_timestamp
      CPR_hash: subject_id
    fillna:
      code:
        column: fill_code
      timestamp:
        column: fill_timestamp
    code_prefix: "P_"

  medication:
    filename: CPMI_Medicin.parquet
    columns_map:
      ATC: code
      Administrationstidspunkt: timestamp
      Bestillingsdato: fill_timestamp
      CPR_hash: subject_id
    fillna:
      timestamp:
        column: fill_timestamp
    code_prefix: "M_"

  labtest:
    filename: CPMI_Labsvar.parquet
    columns_map:
      BestOrd: code
      Prøvetagningstidspunkt: timestamp
      Bestillingsdato: fill_timestamp
      Resultatværdi: numeric_value
      CPR_hash: subject_id
    fillna:
      timestamp:
        column: fill_timestamp
    code_prefix: "L_"
    numeric_columns: [numeric_value]

register_concepts:
  register_diagnosis:
    filename: Diagnoser.parquet
    columns_map:
      diagnosekode: code
      diagnosetype: code_type
    code_prefix: "RD_"
    main_mapping:
      filename: kontakter.parquet
      left_on: dw_ek_kontakt
      right_on: dw_ek_kontakt
    
  register_contacts:
    filename: kontakter.parquet
    columns_map:
      PID: subject_id
      dw_ek_kontakt: dw_ek_kontakt
      dw_ek_forloeb: dw_ek_forloeb
      dato_start: date_start
      tidspunkt_start: time_start
      dato_slut: date_end
      tidspunkt_slut: time_end
      aktionsdiagnose: action_diagnosis
      kontaktaarsage: contact_reason
    combine_datetime:
      admission:
        date_col: date_start
        time_col: time_start
        drop_original: true
      discharge:
        date_col: date_end
        time_col: time_end
        drop_original: true
    unroll_columns:
      - column: enhedstype_ans
        prefix: "RC_UNIT_"
      - column: hovedspeciale_ans
        prefix: "RC_SPEC_"
      - column: regions_ans
        prefix: "RC_REG_"
      - column: action_diagnosis
        prefix: "RC_DIAG_"
      - column: contact_reason
        prefix: "RC_REASON_"

  register_medication:
    filename: epikur.parquet
    columns_map:
      PID: subject_id
      vnr: vnr_code
    secondary_mapping:
      filename: laegemiddeloplysninger.asc
      left_on: vnr_code
      right_on: VNR
    code_prefix: "RM_"

  register_procedures_surgery:
    filename: procedurer_kirurgi.parquet
    columns_map:
      procedurekode: code
      proceduretype: procedure_type
      dato_start: date_start
      tidspunkt_start: time_start
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPS_"
    main_mapping:
      filename: kontakter.parquet
      left_on: dw_ek_kontakt
      right_on: dw_ek_kontakt

  register_procedures_other:
    filename: procedurer_andre.parquet
    columns_map:
      procedurekode: code
      proceduretype: procedure_type
      dato_start: date_start
      tidspunkt_start: time_start
    combine_datetime:
      timestamp:
        date_col: date_start
        time_col: time_start
        drop_original: true
    code_prefix: "RPO_"
    main_mapping:
      filename: kontakter.parquet
      left_on: dw_ek_kontakt
      right_on: dw_ek_kontakt

patients_info:
  filename: CPMI_PatientInfo.parquet
  columns_map:
    CPR_hash: subject_id
    Fødselsdato: birthdate
    Dødsdato: deathdate
    Køn: gender
  file_type: parquet